name: Translate README

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 12.x
      # ISO Langusge Codes: https://cloud.google.com/translate/docs/languages  
      - name: Adding README - Inglese
        uses: dephraiim/translate-readme@main
        with:
          LANG: en
      - name: Adding README - Spagnolo
        uses: dephraiim/translate-readme@main
        with:
          LANG: es
